apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  labels:
    app: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp 
    spec:
      containers:
      - name: nodeserver
        image: thetips4you/nodeapp:latest
        ports:
        - containerPort: 3000
        env:
        - name: MYENV         # env name in which value of the key is stored
          valueFrom:
           configMapKeyRef:
            name: mymap11      # name of the config create 
        volumeMounts:
         - name: testsecret
           mountPath: "/tmp/my-secret-sk"   # the secret files will be mounted as ReadOnly by default here
      volumes:
      - name: testsecret
        secret:
         secretName: secret-sk11
        
        
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
spec:
  selector:
    app: nodeapp 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31110
